# -----------------------------------------------------------------------------
# Copyright Siemens AG, 2021.
# Part of the SW360 Portal Project.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# -----------------------------------------------------------------------------

name: SW360

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  COUCHDB_USER: admin
  COUCHDB_PASSWORD: password

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup CouchDB
      uses: iamssen/couchdb-github-action@master
      with:
          couchdb-version: '3.1'

    - name: Update properties with DB credentials
      run: |
        sudo apt-get update -qq
        sudo sed -i 's/^couchdb.user\s*=/& '${COUCHDB_USER}'/' build-configuration/test-resources/couchdb-test.properties
        sudo sed -i 's/^couchdb.password\s*=/& '${COUCHDB_PASSWORD}'/' build-configuration/test-resources/couchdb-test.properties
        sudo mkdir /etc/sw360
        sudo cp ./scripts/sw360BackendRestDockerConfig/etc_sw360/couchdb-test.properties /etc/sw360/

    - name: Verify license headers
      run: |
        chmod +x .github/testForLicenseHeaders.sh
        bash .github/testForLicenseHeaders.sh

    - name: Install Thrift and mkdocs
      run: |
        sudo apt-get update
        sudo apt-get install python3
        sudo apt-get install python3-pip
        sudo pip3 install mkdocs
        sudo pip3 install mkdocs-material
        chmod +x scripts/install-thrift.sh
        bash scripts/install-thrift.sh --no-cleanup

    - name: Build SW360
      run: mvn clean package --no-transfer-progress -P deploy -Dhelp-docs=true -Dbase.deploy.dir=. -Dliferay.deploy.dir=/home/runner/work/sw360/sw360/deploy -Dbackend.deploy.dir=/home/runner/work/sw360/sw360/webapps -Drest.deploy.dir=/home/runner/work/sw360/sw360/webapps -DRunComponentVisibilityRestrictionTest=false -DRunPrivateProjectAccessTest=false

    - name: Run PrivateProjectAccessTest
      run: |
        cd build-configuration
        mvn install
        cd ..
        cd libraries/lib-datahandler
        mvn test -Dtest=ProjectPermissionsVisibilityTest -DRunPrivateProjectAccessTest=true

    - name: Deploy Backend and Rest Server
      run: |
        sudo docker build -t sw360backendrest -f sw360BackendRest.Dockerfile .
        sudo docker run -dt --network=host sw360backendrest
        bash scripts/sw360BackendRestDockerConfig/scripts/checkDeploymentIsSuccess.sh

    - name: Create users and oauth client
      run: bash scripts/sw360BackendRestDockerConfig/scripts/createUserAndOauthClient.sh

    - name: Run Client Itegration Test for Rest Api
      run: |
        cd clients
        mvn clean install --no-transfer-progress -DRunRestIntegrationTest=true

