# -----------------------------------------------------------------------------
# Copyright Siemens AG, 2021.
# Part of the SW360 Portal Project.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# -----------------------------------------------------------------------------

name: SW360

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  COUCHDB_USER: admin
  COUCHDB_PASSWORD: password

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup CouchDB
      uses: iamssen/couchdb-github-action@master
      with:
          couchdb-version: '3.1'

    - name: Update properties with DB credentials
      run: |
        sudo sed -i 's/^couchdb.user\s*=/& '${COUCHDB_USER}'/' build-configuration/test-resources/couchdb-test.properties
        sudo sed -i 's/^couchdb.password\s*=/& '${COUCHDB_PASSWORD}'/' build-configuration/test-resources/couchdb-test.properties
        sudo mkdir -p /etc/sw360
        sudo cp ./scripts/sw360BackendRestDockerConfig/etc_sw360/couchdb-test.properties /etc/sw360/

    - name: Set up JDK 11
      run: |
        wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | sudo tee /usr/share/keyrings/adoptium.asc
        echo "deb [signed-by=/usr/share/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | sudo tee /etc/apt/sources.list.d/adoptium.list

    - name: Prepare build environment
      run: |
        sudo apt-get update -qq
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq python3-pip build-essential libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config libssl-dev git temurin-11-jdk maven
        pip install mkdocs mkdocs-material

    - name: Verify license headers
      run: |
        chmod +x .github/testForLicenseHeaders.sh
        bash .github/testForLicenseHeaders.sh

    - name: Install Thrift
      run: |
        chmod +x scripts/install-thrift.sh
        bash scripts/install-thrift.sh --no-cleanup

    - name: Build SW360
      run: mvn clean package --no-transfer-progress -P deploy -Dhelp-docs=true -Dbase.deploy.dir=. -Dliferay.deploy.dir=${PWD}/deploy -Dbackend.deploy.dir=${PWD}/deploy/webapps -Drest.deploy.dir=${PWD}/deploy/webapps -DRunComponentVisibilityRestrictionTest=false -DRunPrivateProjectAccessTest=false

    - name: Run PrivateProjectAccessTest
      run: |
        cd build-configuration
        mvn install
        cd ..
        cd libraries/lib-datahandler
        mvn test -Dtest=ProjectPermissionsVisibilityTest -DRunPrivateProjectAccessTest=true

    - name: Deploy Backend and Rest Server
      run: |
        sudo docker build -t sw360backendrest -f sw360BackendRest.Dockerfile .
        sudo docker run -dt --network=host sw360backendrest
        bash scripts/sw360BackendRestDockerConfig/scripts/checkDeploymentIsSuccess.sh

    - name: Create users and oauth client
      run: bash scripts/sw360BackendRestDockerConfig/scripts/createUserAndOauthClient.sh

    - name: Run Client Integration Test for Rest Api
      run: |
        cd clients
        mvn clean install --no-transfer-progress -DRunRestIntegrationTest=true

